version: "3.9"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - SUBDOMAINS=${SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
  swag:
    # Create configs from https://github.com/linuxserver/reverse-proxy-confs
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - URL=${HOSTNAME}
      - VALIDATION=duckdns
      - SUBDOMAINS=wildcard
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - EMAIL=${ADMIN_EMAIL}
      - CERTPROVIDER=zerossl
    volumes:
      - swag_nginx:/config/nginx
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    volumes:
      - swag_nginx:/swag
    ports:
      - 3000:3000
    restart: unless-stopped
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    volumes:
      - syncthing_config:/config
      - books:/data/books
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    volumes:
      - ./heimdall:/config
    restart: always

networks:
  default:
    name: compose-nas

volumes:
  swag_nginx:
    driver_opts:
      type: cifs
      o: "username=${SMB_USER},password=${SMB_PASS},addr=${SMB_SRV},noperm"
      device: "//${SMB_SRV}/fast/swag_nginx"
  syncthing_config:
    driver_opts:
      type: cifs
      o: "username=${SMB_USER},password=${SMB_PASS},addr=${SMB_SRV},noperm"
      device: "//${SMB_SRV}/fast/syncthing_config"
  books:
    driver_opts:
      type: cifs
      o: "username=${SMB_USER},password=${SMB_PASS},addr=${SMB_SRV},noperm"
      device: "//${SMB_SRV}/Books"