services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - /mnt/media/audiobooks:/audiobooks
      - /mnt/media/podcasts:/podcasts
      - config:/config
      - metadata:/metadata

networks:
  default:
    name: compose-nas
    external: true

volumes:
  config:
  metadata:
