services:
  filebrowser:
    image: pldubouilh/gossa
    container_name: filebrowser
    user: 1000:1000
    volumes:
      - /mnt/media/audiobooks:/shared/audiobooks
      - /mnt/media/books:/shared/books
      - /mnt/media/movies:/shared/movies
      - /mnt/media/music:/shared/music
      - /mnt/media/podcasts:/shared/podcasts
      - /mnt/media/photos:/shared/photos
      - /mnt/media/shows:/shared/shows
      - /mnt/media/shared:/shared/shared
    restart: unless-stopped

networks:
  default:
    name: compose-nas
    external: true