services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    networks:
      - default
      - nas
    environment:
      - APP_URL=https://bookstack.${HOSTNAME}
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${BOOKSTACK_DB_PASS}
      - DB_DATABASE=bookstackapp
      - AUTH_METHOD=oidc
      - OIDC_NAME=Authelia
      - OIDC_DISPLAY_NAME_CLAIMS=name
      - OIDC_CLIENT_ID=bookstack
      - OIDC_CLIENT_SECRET=${BOOKSTACK_OIDC_SECRET}
      - OIDC_ISSUER=https://auth.${HOSTNAME}
      - OIDC_ISSUER_DISCOVER='true'
    volumes:
      - app:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_DB_ADMINPASS}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASS}
    volumes:
      - db:/config
    restart: unless-stopped

networks:
  default:
  nas:
    name: compose-nas
    external: true

volumes:
  db:
  app: